Rhondene Wint
Oct 2018
## Implementing Deep learning applications in Keras (IBM Coursera)

Gone are the days when I had code each layer scratch and doing all sorts of winded sanity checks..mwah hahahaha!

In [7]:
import tensorflow
import keras
import pandas 
import numpy

In [2]:
import keras

## Sentiment classification of  movie reviews from imbdb us LSTM

- Need an <b> embedding layer </b> which is used in the first layer. The embedding layer transforms integers to vectors of the same length. In this case, we want to embed a vocabulary into vector space which then fed to LSTM model


<p> Data Space </p>
- 25,00 movie revies from IMDB, labelled good or bad
- Data is available from keras.datasets
- Data is preprocessed as sequences of integers
- Task: classify sentiment from review content
Embed sentences with embedding layer --> learn sentence structure wth LSTM

In [8]:
from keras.layers.recurrent import LSTM
from keras.layers import Dense, Embedding
from keras.datasets import imdb
from keras.models import Sequential

In [4]:
max_features = 20000 #20,000 most common from vocabulary
maxlen = 80   #
#load imdb into memory 
(x_train, y_train), (x_test, y_test)=imdb.load_data(num_words=max_features)

In [6]:
x_train[0];

In [9]:
##preprocessing, padding to get on same length
from keras.preprocessing import sequence
x_train= sequence.pad_sequences(x_train, maxlen=maxlen)
x_test = sequence.pad_sequences(x_test, maxlen=maxlen)

In [13]:
#instantiate and build model
model=Sequential()
model.add(Embedding(max_features, 128))
model.add(LSTM(128, dropout=0.2, recurrent_dropout=0.2))
model.add(Dense(1, activation='sigmoid')) #FNN classier

In [14]:
##compile the moodel with loss function and optimizer
model.compile(loss='binary_crossentropy',
             optimizer='sgd',
             metrics=['accuracy'])

In [15]:
##fit the model to data now
model.fit(x_train, y_train,
         batch_size=32,
         epochs=15,
         validation_data=(x_test, y_test))

Train on 25000 samples, validate on 25000 samples
Epoch 1/15
25000/25000 [==============================] - 128s 5ms/step - loss: 0.6932 - acc: 0.5025 - val_loss: 0.6931 - val_acc: 0.5029
Epoch 2/15
25000/25000 [==============================] - 124s 5ms/step - loss: 0.6930 - acc: 0.5076 - val_loss: 0.6930 - val_acc: 0.5001
Epoch 3/15
25000/25000 [==============================] - 124s 5ms/step - loss: 0.6928 - acc: 0.5158 - val_loss: 0.6927 - val_acc: 0.5352
Epoch 4/15
25000/25000 [==============================] - 124s 5ms/step - loss: 0.6926 - acc: 0.5250 - val_loss: 0.6925 - val_acc: 0.5265
Epoch 5/15
25000/25000 [==============================] - 125s 5ms/step - loss: 0.6924 - acc: 0.5321 - val_loss: 0.6923 - val_acc: 0.5356
Epoch 6/15
25000/25000 [==============================] - 125s 5ms/step - loss: 0.6921 - acc: 0.5372 - val_loss: 0.6920 - val_acc: 0.5428
Epoch 7/15
25000/25000 [==============================] - 125s 5ms/step - loss: 0.6918 - acc: 0.5354 - val_loss: 0.6920 - 

In [16]:
##evaluate the model
model.evaluate(x_test, y_test, batch_size=32)

25000/25000 [==============================] - 22s 888us/step


[0.6870271743774414, 0.59624]

oct 21
# Using Autoencoder with Word2Vec


In [9]:
from keras.models import Sequential
from keras.layers import Dense, Embedding,Flatten, Input
from keras.preprocessing.text import one_hot
from keras.optimizers import Adam
from sklearn.preprocessing import OneHotEncoder

In [10]:
#define document with 5 sentences,
docs = ['king is a man', 'a queen is a woman', 'king marries queen','you on some bullshit','queen marries king']

In [11]:
vocab_size = 50 #this systme will support 50 unique words, IRL it's 100Ks english words

In [13]:
##convert the words to unique integers
oh = numpy.array(one_hot('king queen man unrelated', vocab_size)).reshape(-1,1)

In [14]:
oh

array([[15],
       [22],
       [48],
       [21]])

In [17]:
##now apply actual Onehot to return sparse representation of words
enc = OneHotEncoder()
enc.fit(numpy.array(range(50)).reshape(-1,1))
oh_enc = enc.transform(oh).toarray()
oh_enc

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.]])

In [18]:
##let's do for the actual wordsb
encoded_docs = [one_hot(d,vocab_size) for d in docs]
encoded_docs

[[15, 10, 27, 48],
 [27, 22, 10, 27, 14],
 [15, 26, 22],
 [27, 25, 10, 27],
 [22, 26, 15]]

each element is a sentence in this multidimensional array is a sentence and each integer is a word 
for example number 15 is is 'king' which is found in 1st and 3rd sentences

In [21]:
##padding to make sentences same lenght
from keras.preprocessing.sequence import pad_sequences
max_len = 24
padded_docs = pad_sequences(encoded_docs,maxlen=max_len, padding='post')

In [26]:
##create tuples of related words based on neigbours of the words..usefule for my codon analysis 
tuples = numpy.empty((0,2))
for padded_doc in padded_docs:
    length = len(padded_doc)
    for i in range(length):
        if padded_doc[i] != 0:
            if i< length-1 & padded_doc[i+1]!=0:
                tuples = numpy.append(tuples,[[padded_doc[i], padded_doc[i+1]]], axis=0)
                if i<length-2 & padded_doc[i+2]!=0:
                    tuples = numpy.append(tuples, [[padded_doc[i], padded_doc[i+2]]], axis=0)
            if i >0:
                tuples = numpy.append(tuples, [[padded_doc[i], padded_doc[i-1]]], axis=0)
            if i>1:
                tuples = numpy.append(tuples, [[padded_doc[i], padded_doc[i-2]]], axis=0)
print(tuples.shape)
tuples

(46, 2)


array([[15., 10.],
       [15., 27.],
       [10., 27.],
       [10., 48.],
       [10., 15.],
       [27., 48.],
       [27., 10.],
       [27., 15.],
       [48., 27.],
       [48., 10.],
       [27., 22.],
       [27., 10.],
       [22., 10.],
       [22., 27.],
       [22., 27.],
       [10., 27.],
       [10., 14.],
       [10., 22.],
       [10., 27.],
       [27., 14.],
       [27., 10.],
       [27., 22.],
       [14., 27.],
       [14., 10.],
       [15., 26.],
       [15., 22.],
       [26., 22.],
       [26., 15.],
       [22., 26.],
       [22., 15.],
       [27., 25.],
       [27., 10.],
       [25., 10.],
       [25., 27.],
       [25., 27.],
       [10., 27.],
       [10., 25.],
       [10., 27.],
       [27., 10.],
       [27., 25.],
       [22., 26.],
       [22., 15.],
       [26., 15.],
       [26., 22.],
       [15., 26.],
       [15., 22.]])

In [27]:
##onehot encode the first dimension of the tuple as input X 
onehotlabels_x = enc.transform(tuples[:,0].reshape(-1,1)).toarray()
print(onehotlabels_x.shape)

(46, 50)


In [28]:
##onehot encode the first dimension of the tuple as y, this is what we want to predict 
onehotlabels_y = enc.transform(tuples[:,1].reshape(-1,1)).toarray()
print(onehotlabels_y.shape)

(46, 50)


In [35]:
##build and compile the model

model= Sequential()

input = Dense(50, input_shape=(50,), activation='relu')  #iunput layer
model.add(input)
bottleneck= Dense(2, activation='relu')   #low-dimensional representation of the word embedding 
model.add(bottleneck)
model.add(Dense(50, activation='softmax'))  #output has to be dimension 50 since output was 50

#model.add(Embedding(vocab_size, 8, input_length=max_length))
#model.add(Flatten())
#model.add(Dense(1, activation='sigmoid'))
#compile the model

model.compile(optimizer='adam', loss='binary_crossentropy',metrics=['acc'])
#sumarise the model
print(model.summary())

#fit the model
model.fit(onehotlabels_x, onehotlabels_y, epochs=25, verbose=1)

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_4 (Dense)              (None, 50)                2550      
_________________________________________________________________
dense_5 (Dense)              (None, 2)                 102       
_________________________________________________________________
dense_6 (Dense)              (None, 50)                150       
Total params: 2,802
Trainable params: 2,802
Non-trainable params: 0
_________________________________________________________________
None
Epoch 1/25
46/46 [==============================] - 3s 67ms/step - loss: 0.0982 - acc: 0.9800
Epoch 2/25
46/46 [==============================] - 0s 489us/step - loss: 0.0981 - acc: 0.9800
Epoch 3/25
46/46 [==============================] - 0s 163us/step - loss: 0.0980 - acc: 0.9800
Epoch 4/25
46/46 [==============================] - 0s 272us/step - loss: 0.0979 - acc: 0.9800
Epoch 5/25
46/46 [==

In [37]:

model = Sequential()
model.add(input)
model.add(bottleneck)  #reuse already trained layers
model.compile(optimizer=Adam(lr=0.001), loss='binary_crossentropy', metrics=['acc'])

test = model.predict(oh_enc)   #the previous 5 word sentence
##we can perform arithmetic on word embeddings
print(test)  #sd representation of the words


[[0.         0.4969879 ]
 [0.         0.00333944]
 [0.03422897 0.22597976]
 [0.         0.19172534]]


In [41]:
#define docs
print(test[0,:]-test[2,:]+test[3,:]-test[2,:])  #king-man+woman ~= queen

[-0.06845795  0.23675372]


### Sentiment Text Classification with Keras pt2,
#### classify wheether docmunet is positive or negtaive

In [42]:
model = Sequential()
model.add(Embedding(1000,3,input_length=5))  #create low-dime represntion for is 
model.compile(optimizer='rmsprop', loss= 'mse')

input_array = numpy.random.randint(1000,size=(3,5))
input_array

array([[764, 656, 434, 322,  30],
       [424, 974, 742, 244, 583],
       [827, 457, 620,   7, 357]])

In [43]:
output_array = model.predict(input_array)
output_array.shape #3D tensor, the first element is a sentence and each word has 3-dimension 

(3, 5, 3)

In [45]:
#define documents

docs = ['Well done!',
       'Good Work',
       'Great effort',
       'nice work',
       'Excellent',
       'weak',
       'poor work',
       'Poor Effort!',
       'not good','Could have done better.']
#define class labels
labels = [1,1,1,1,1,0,0,0,0,0]

In [46]:
#ecnode the documents as integers
vocab_size = 50
encoded_docs = [one_hot(d,vocab_size) for d in docs]
print(encoded_docs)

[[24, 23], [29, 5], [18, 6], [10, 5], [10], [38], [23, 5], [23, 6], [15, 29], [24, 46, 23, 32]]


In [47]:
##padding
max_len = 4  #the longest sentence has 4
padded_docs = pad_sequences(encoded_docs, maxlen=max_len, padding='post')
print(padded_docs)

[[24 23  0  0]
 [29  5  0  0]
 [18  6  0  0]
 [10  5  0  0]
 [10  0  0  0]
 [38  0  0  0]
 [23  5  0  0]
 [23  6  0  0]
 [15 29  0  0]
 [24 46 23 32]]


In [48]:
model = Sequential()

model.add(Embedding(vocab_size,8, input_length=max_len))
model.add(Flatten())   #unroll 3d tensor into 1-d 
model.add(Dense(1,activation='sigmoid'))

#compile the model

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])

print(model.summary())

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (None, 4, 8)              400       
_________________________________________________________________
flatten_1 (Flatten)          (None, 32)                0         
_________________________________________________________________
dense_7 (Dense)              (None, 1)                 33        
Total params: 433
Trainable params: 433
Non-trainable params: 0
_________________________________________________________________
None


In [49]:
#fit model
model.fit(padded_docs, labels, epochs=20, verbose=0)
#evaluate model
loss,accuracy = model.evaluate(padded_docs, labels,verbose=0)

print('Accuracy: ', (accuracy*100))

Accuracy:  80.0000011920929
